#! /usr/bin/env python
# encoding: utf-8

def options(opt):
    opt.load( 'compiler_c' )

def configure(conf):
    conf.load( 'compiler_c' )

def build(bld):
    bld.program(
        source=[
            'main.c',
            'number.c',
            'pthLocker.c',
            'pthTextCode.c',
            'pthTextRW.c'
            ],
        includes='./',
        lib='pthread',
        libpath='/usr/lib',
        target='Locker',
        cflags=[
            '-gdwarf-2',
            '-DDEBUG'
            ],
        install_path='./'
    )
