/*
 * Generated by gdbus-codegen 2.56.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "DbusTest_code.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.example.qdbus.wtest
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:OrgExampleQdbusWtest
 * @title: OrgExampleQdbusWtest
 * @short_description: Generated C code for the org.example.qdbus.wtest D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-example-qdbus-wtest.top_of_page">org.example.qdbus.wtest</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.example.qdbus.wtest ---- */

static const _ExtendedGDBusArgInfo _org_example_qdbus_wtest_method_info_set_value_IN_ARG_newValue =
{
  {
    -1,
    (gchar *) "newValue",
    (gchar *) "d",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_example_qdbus_wtest_method_info_set_value_IN_ARG_pointers[] =
{
  &_org_example_qdbus_wtest_method_info_set_value_IN_ARG_newValue,
  NULL
};

static const _ExtendedGDBusMethodInfo _org_example_qdbus_wtest_method_info_set_value =
{
  {
    -1,
    (gchar *) "setValue",
    (GDBusArgInfo **) &_org_example_qdbus_wtest_method_info_set_value_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-value",
  FALSE
};

static const _ExtendedGDBusMethodInfo _org_example_qdbus_wtest_method_info_get_value =
{
  {
    -1,
    (gchar *) "getValue",
    NULL,
    NULL,
    NULL
  },
  "handle-get-value",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _org_example_qdbus_wtest_method_info_pointers[] =
{
  &_org_example_qdbus_wtest_method_info_set_value,
  &_org_example_qdbus_wtest_method_info_get_value,
  NULL
};

static const _ExtendedGDBusArgInfo _org_example_qdbus_wtest_signal_info_value_changed_ARG_newValue =
{
  {
    -1,
    (gchar *) "newValue",
    (gchar *) "d",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_example_qdbus_wtest_signal_info_value_changed_ARG_pointers[] =
{
  &_org_example_qdbus_wtest_signal_info_value_changed_ARG_newValue,
  NULL
};

static const _ExtendedGDBusSignalInfo _org_example_qdbus_wtest_signal_info_value_changed =
{
  {
    -1,
    (gchar *) "valueChanged",
    (GDBusArgInfo **) &_org_example_qdbus_wtest_signal_info_value_changed_ARG_pointers,
    NULL
  },
  "value-changed"
};

static const _ExtendedGDBusSignalInfo * const _org_example_qdbus_wtest_signal_info_pointers[] =
{
  &_org_example_qdbus_wtest_signal_info_value_changed,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _org_example_qdbus_wtest_interface_info =
{
  {
    -1,
    (gchar *) "org.example.qdbus.wtest",
    (GDBusMethodInfo **) &_org_example_qdbus_wtest_method_info_pointers,
    (GDBusSignalInfo **) &_org_example_qdbus_wtest_signal_info_pointers,
    NULL,
    NULL
  },
  "org-example-qdbus-wtest",
};


/**
 * org_example_qdbus_wtest_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-example-qdbus-wtest.top_of_page">org.example.qdbus.wtest</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
org_example_qdbus_wtest_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_org_example_qdbus_wtest_interface_info.parent_struct;
}

/**
 * org_example_qdbus_wtest_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #OrgExampleQdbusWtest interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
org_example_qdbus_wtest_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * OrgExampleQdbusWtest:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-example-qdbus-wtest.top_of_page">org.example.qdbus.wtest</link>.
 */

/**
 * OrgExampleQdbusWtestIface:
 * @parent_iface: The parent interface.
 * @handle_get_value: Handler for the #OrgExampleQdbusWtest::handle-get-value signal.
 * @handle_set_value: Handler for the #OrgExampleQdbusWtest::handle-set-value signal.
 * @value_changed: Handler for the #OrgExampleQdbusWtest::value-changed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-example-qdbus-wtest.top_of_page">org.example.qdbus.wtest</link>.
 */

typedef OrgExampleQdbusWtestIface OrgExampleQdbusWtestInterface;
G_DEFINE_INTERFACE (OrgExampleQdbusWtest, org_example_qdbus_wtest, G_TYPE_OBJECT)

static void
org_example_qdbus_wtest_default_init (OrgExampleQdbusWtestIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * OrgExampleQdbusWtest::handle-set-value:
   * @object: A #OrgExampleQdbusWtest.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_newValue: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-example-qdbus-wtest.setValue">setValue()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call org_example_qdbus_wtest_complete_set_value() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-value",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgExampleQdbusWtestIface, handle_set_value),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_DOUBLE);

  /**
   * OrgExampleQdbusWtest::handle-get-value:
   * @object: A #OrgExampleQdbusWtest.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-example-qdbus-wtest.getValue">getValue()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call org_example_qdbus_wtest_complete_get_value() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-value",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgExampleQdbusWtestIface, handle_get_value),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /* GObject signals for received D-Bus signals: */
  /**
   * OrgExampleQdbusWtest::value-changed:
   * @object: A #OrgExampleQdbusWtest.
   * @arg_newValue: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-example-qdbus-wtest.valueChanged">"valueChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("value-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgExampleQdbusWtestIface, value_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_DOUBLE);

}

/**
 * org_example_qdbus_wtest_emit_value_changed:
 * @object: A #OrgExampleQdbusWtest.
 * @arg_newValue: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-example-qdbus-wtest.valueChanged">"valueChanged"</link> D-Bus signal.
 */
void
org_example_qdbus_wtest_emit_value_changed (
    OrgExampleQdbusWtest *object,
    gdouble arg_newValue)
{
  g_signal_emit_by_name (object, "value-changed", arg_newValue);
}

/**
 * org_example_qdbus_wtest_call_set_value:
 * @proxy: A #OrgExampleQdbusWtestProxy.
 * @arg_newValue: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-example-qdbus-wtest.setValue">setValue()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_example_qdbus_wtest_call_set_value_finish() to get the result of the operation.
 *
 * See org_example_qdbus_wtest_call_set_value_sync() for the synchronous, blocking version of this method.
 */
void
org_example_qdbus_wtest_call_set_value (
    OrgExampleQdbusWtest *proxy,
    gdouble arg_newValue,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "setValue",
    g_variant_new ("(d)",
                   arg_newValue),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * org_example_qdbus_wtest_call_set_value_finish:
 * @proxy: A #OrgExampleQdbusWtestProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_example_qdbus_wtest_call_set_value().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with org_example_qdbus_wtest_call_set_value().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_example_qdbus_wtest_call_set_value_finish (
    OrgExampleQdbusWtest *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_example_qdbus_wtest_call_set_value_sync:
 * @proxy: A #OrgExampleQdbusWtestProxy.
 * @arg_newValue: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-example-qdbus-wtest.setValue">setValue()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See org_example_qdbus_wtest_call_set_value() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_example_qdbus_wtest_call_set_value_sync (
    OrgExampleQdbusWtest *proxy,
    gdouble arg_newValue,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "setValue",
    g_variant_new ("(d)",
                   arg_newValue),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_example_qdbus_wtest_call_get_value:
 * @proxy: A #OrgExampleQdbusWtestProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-example-qdbus-wtest.getValue">getValue()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_example_qdbus_wtest_call_get_value_finish() to get the result of the operation.
 *
 * See org_example_qdbus_wtest_call_get_value_sync() for the synchronous, blocking version of this method.
 */
void
org_example_qdbus_wtest_call_get_value (
    OrgExampleQdbusWtest *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "getValue",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * org_example_qdbus_wtest_call_get_value_finish:
 * @proxy: A #OrgExampleQdbusWtestProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_example_qdbus_wtest_call_get_value().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with org_example_qdbus_wtest_call_get_value().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_example_qdbus_wtest_call_get_value_finish (
    OrgExampleQdbusWtest *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_example_qdbus_wtest_call_get_value_sync:
 * @proxy: A #OrgExampleQdbusWtestProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-example-qdbus-wtest.getValue">getValue()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See org_example_qdbus_wtest_call_get_value() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_example_qdbus_wtest_call_get_value_sync (
    OrgExampleQdbusWtest *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "getValue",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_example_qdbus_wtest_complete_set_value:
 * @object: A #OrgExampleQdbusWtest.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-example-qdbus-wtest.setValue">setValue()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
org_example_qdbus_wtest_complete_set_value (
    OrgExampleQdbusWtest *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * org_example_qdbus_wtest_complete_get_value:
 * @object: A #OrgExampleQdbusWtest.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-example-qdbus-wtest.getValue">getValue()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
org_example_qdbus_wtest_complete_get_value (
    OrgExampleQdbusWtest *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * OrgExampleQdbusWtestProxy:
 *
 * The #OrgExampleQdbusWtestProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * OrgExampleQdbusWtestProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #OrgExampleQdbusWtestProxy.
 */

struct _OrgExampleQdbusWtestProxyPrivate
{
  GData *qdata;
};

static void org_example_qdbus_wtest_proxy_iface_init (OrgExampleQdbusWtestIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (OrgExampleQdbusWtestProxy, org_example_qdbus_wtest_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (OrgExampleQdbusWtestProxy)
                         G_IMPLEMENT_INTERFACE (TYPE_ORG_EXAMPLE_QDBUS_WTEST, org_example_qdbus_wtest_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (OrgExampleQdbusWtestProxy, org_example_qdbus_wtest_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_ORG_EXAMPLE_QDBUS_WTEST, org_example_qdbus_wtest_proxy_iface_init))

#endif
static void
org_example_qdbus_wtest_proxy_finalize (GObject *object)
{
  OrgExampleQdbusWtestProxy *proxy = ORG_EXAMPLE_QDBUS_WTEST_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (org_example_qdbus_wtest_proxy_parent_class)->finalize (object);
}

static void
org_example_qdbus_wtest_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
org_example_qdbus_wtest_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
org_example_qdbus_wtest_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_org_example_qdbus_wtest_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_ORG_EXAMPLE_QDBUS_WTEST);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_ORG_EXAMPLE_QDBUS_WTEST);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
org_example_qdbus_wtest_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  OrgExampleQdbusWtestProxy *proxy = ORG_EXAMPLE_QDBUS_WTEST_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_example_qdbus_wtest_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_example_qdbus_wtest_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
org_example_qdbus_wtest_proxy_init (OrgExampleQdbusWtestProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = org_example_qdbus_wtest_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_ORG_EXAMPLE_QDBUS_WTEST_PROXY, OrgExampleQdbusWtestProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), org_example_qdbus_wtest_interface_info ());
}

static void
org_example_qdbus_wtest_proxy_class_init (OrgExampleQdbusWtestProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = org_example_qdbus_wtest_proxy_finalize;
  gobject_class->get_property = org_example_qdbus_wtest_proxy_get_property;
  gobject_class->set_property = org_example_qdbus_wtest_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = org_example_qdbus_wtest_proxy_g_signal;
  proxy_class->g_properties_changed = org_example_qdbus_wtest_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (OrgExampleQdbusWtestProxyPrivate));
#endif
}

static void
org_example_qdbus_wtest_proxy_iface_init (OrgExampleQdbusWtestIface *iface)
{
}

/**
 * org_example_qdbus_wtest_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-example-qdbus-wtest.top_of_page">org.example.qdbus.wtest</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_example_qdbus_wtest_proxy_new_finish() to get the result of the operation.
 *
 * See org_example_qdbus_wtest_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
org_example_qdbus_wtest_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_ORG_EXAMPLE_QDBUS_WTEST_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.example.qdbus.wtest", NULL);
}

/**
 * org_example_qdbus_wtest_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_example_qdbus_wtest_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with org_example_qdbus_wtest_proxy_new().
 *
 * Returns: (transfer full) (type OrgExampleQdbusWtestProxy): The constructed proxy object or %NULL if @error is set.
 */
OrgExampleQdbusWtest *
org_example_qdbus_wtest_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return ORG_EXAMPLE_QDBUS_WTEST (ret);
  else
    return NULL;
}

/**
 * org_example_qdbus_wtest_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-example-qdbus-wtest.top_of_page">org.example.qdbus.wtest</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See org_example_qdbus_wtest_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type OrgExampleQdbusWtestProxy): The constructed proxy object or %NULL if @error is set.
 */
OrgExampleQdbusWtest *
org_example_qdbus_wtest_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_ORG_EXAMPLE_QDBUS_WTEST_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.example.qdbus.wtest", NULL);
  if (ret != NULL)
    return ORG_EXAMPLE_QDBUS_WTEST (ret);
  else
    return NULL;
}


/**
 * org_example_qdbus_wtest_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like org_example_qdbus_wtest_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_example_qdbus_wtest_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See org_example_qdbus_wtest_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
org_example_qdbus_wtest_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_ORG_EXAMPLE_QDBUS_WTEST_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.example.qdbus.wtest", NULL);
}

/**
 * org_example_qdbus_wtest_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_example_qdbus_wtest_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with org_example_qdbus_wtest_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type OrgExampleQdbusWtestProxy): The constructed proxy object or %NULL if @error is set.
 */
OrgExampleQdbusWtest *
org_example_qdbus_wtest_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return ORG_EXAMPLE_QDBUS_WTEST (ret);
  else
    return NULL;
}

/**
 * org_example_qdbus_wtest_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like org_example_qdbus_wtest_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See org_example_qdbus_wtest_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type OrgExampleQdbusWtestProxy): The constructed proxy object or %NULL if @error is set.
 */
OrgExampleQdbusWtest *
org_example_qdbus_wtest_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_ORG_EXAMPLE_QDBUS_WTEST_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.example.qdbus.wtest", NULL);
  if (ret != NULL)
    return ORG_EXAMPLE_QDBUS_WTEST (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * OrgExampleQdbusWtestSkeleton:
 *
 * The #OrgExampleQdbusWtestSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * OrgExampleQdbusWtestSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #OrgExampleQdbusWtestSkeleton.
 */

struct _OrgExampleQdbusWtestSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_org_example_qdbus_wtest_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  OrgExampleQdbusWtestSkeleton *skeleton = ORG_EXAMPLE_QDBUS_WTEST_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_ORG_EXAMPLE_QDBUS_WTEST);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_ORG_EXAMPLE_QDBUS_WTEST);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_org_example_qdbus_wtest_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  OrgExampleQdbusWtestSkeleton *skeleton = ORG_EXAMPLE_QDBUS_WTEST_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_example_qdbus_wtest_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_org_example_qdbus_wtest_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  OrgExampleQdbusWtestSkeleton *skeleton = ORG_EXAMPLE_QDBUS_WTEST_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_example_qdbus_wtest_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _org_example_qdbus_wtest_skeleton_vtable =
{
  _org_example_qdbus_wtest_skeleton_handle_method_call,
  _org_example_qdbus_wtest_skeleton_handle_get_property,
  _org_example_qdbus_wtest_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
org_example_qdbus_wtest_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return org_example_qdbus_wtest_interface_info ();
}

static GDBusInterfaceVTable *
org_example_qdbus_wtest_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_org_example_qdbus_wtest_skeleton_vtable;
}

static GVariant *
org_example_qdbus_wtest_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  OrgExampleQdbusWtestSkeleton *skeleton = ORG_EXAMPLE_QDBUS_WTEST_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_org_example_qdbus_wtest_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _org_example_qdbus_wtest_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _org_example_qdbus_wtest_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _org_example_qdbus_wtest_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.example.qdbus.wtest", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
org_example_qdbus_wtest_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_org_example_qdbus_wtest_on_signal_value_changed (
    OrgExampleQdbusWtest *object,
    gdouble arg_newValue)
{
  OrgExampleQdbusWtestSkeleton *skeleton = ORG_EXAMPLE_QDBUS_WTEST_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(d)",
                   arg_newValue));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.example.qdbus.wtest", "valueChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void org_example_qdbus_wtest_skeleton_iface_init (OrgExampleQdbusWtestIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (OrgExampleQdbusWtestSkeleton, org_example_qdbus_wtest_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (OrgExampleQdbusWtestSkeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_ORG_EXAMPLE_QDBUS_WTEST, org_example_qdbus_wtest_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (OrgExampleQdbusWtestSkeleton, org_example_qdbus_wtest_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_ORG_EXAMPLE_QDBUS_WTEST, org_example_qdbus_wtest_skeleton_iface_init))

#endif
static void
org_example_qdbus_wtest_skeleton_finalize (GObject *object)
{
  OrgExampleQdbusWtestSkeleton *skeleton = ORG_EXAMPLE_QDBUS_WTEST_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (org_example_qdbus_wtest_skeleton_parent_class)->finalize (object);
}

static void
org_example_qdbus_wtest_skeleton_init (OrgExampleQdbusWtestSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = org_example_qdbus_wtest_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_ORG_EXAMPLE_QDBUS_WTEST_SKELETON, OrgExampleQdbusWtestSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
org_example_qdbus_wtest_skeleton_class_init (OrgExampleQdbusWtestSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = org_example_qdbus_wtest_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = org_example_qdbus_wtest_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = org_example_qdbus_wtest_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = org_example_qdbus_wtest_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = org_example_qdbus_wtest_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (OrgExampleQdbusWtestSkeletonPrivate));
#endif
}

static void
org_example_qdbus_wtest_skeleton_iface_init (OrgExampleQdbusWtestIface *iface)
{
  iface->value_changed = _org_example_qdbus_wtest_on_signal_value_changed;
}

/**
 * org_example_qdbus_wtest_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-example-qdbus-wtest.top_of_page">org.example.qdbus.wtest</link>.
 *
 * Returns: (transfer full) (type OrgExampleQdbusWtestSkeleton): The skeleton object.
 */
OrgExampleQdbusWtest *
org_example_qdbus_wtest_skeleton_new (void)
{
  return ORG_EXAMPLE_QDBUS_WTEST (g_object_new (TYPE_ORG_EXAMPLE_QDBUS_WTEST_SKELETON, NULL));
}

